### ISSUE TITLE
Doesn't work with images

### ISSUE THREAD

**Issue by BanchouBoo** [phillbush/xcliputils#1]
When copying images, they get stored as plain text so you can't for example copy a screenshot then paste it into an image editor.

**Comment by phillbush** [comment]
I can copy from Firefox into GIMP with no problems.
I faced a problem, however, on X11 clients that do not support the `MULTIPLE` target, like [`xclip`](https://github.com/milki/xclip) (`xclipd` needs that the clipboard source supports the `MULTIPLE` target).

What are the clipboard source application (the one you `Ctrl-C`) and the clipboard destination application (the one you `Ctrl-V`)?

**Comment by BanchouBoo** [comment]
Using `xclip` with the `image/png` target to copy, pasting into Discord and GIMP both did not work.

**Comment by phillbush** [comment]
Yeah, as I supposed: `xclip`.
It lacks support for the `MULTIPLE` target.
There's [an issue there for that](https://github.com/astrand/xclip/issues/93).

If copying images works between other applications (say from Firefox to GIMP) but not from `xclip`, then that's not a bug on `xclipd` side, but on `xclip`'s. (Although they are named alike, those projects are not related).

I can make a workaround for clients that does not support the `MULTIPLE` target, but that's a hack. The optimal solution is to all X11 clients engaging into the clipboard selection mechanism to implement the ICCCM selection protocol.

**Comment by BanchouBoo** [comment]
Copying does work between applications, guess I'll close this then. Any recommendations for an `xclip` alternative?

**Comment by phillbush** [comment]
> Copying does work between applications, guess I'll close this then. Any recommendations for an `xclip` alternative?

The only X11 clients that work as source and destination for the clipboard are `xclip` and `xsel`.
`xsel`, however, seems to not support targets provided by the user.

I want to expand `xclipd` in the future with two more commands, one for writing into the clipboard, and the other for reading from the clipboard, thus providing replacements for `xclip -in` and `xclip -out`. Those commands will implement the full ICCCM specification, and thus work with other programs.

However, I have implemented into `xclipd` a solution to work with `xclip` and other clients which do not fully implement the ICCCM specification. More information in [the commit message](https://github.com/phillbush/xclipd/commit/680c5975748c60af49cb133a30af0c9ea8ff93fc).

**Comment by BanchouBoo** [comment]
Works now, thanks!

**Comment by phillbush** [comment]
Hi, `xclipd`  is now included with a few other utilities, two of which, `xclipin` and `xclipout` can replace `xclip -in` and `xclip -out` commands.  
`xclipd` still works with not fully ICCCM-compliant applications such as `xclip`.
